// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNcV_-2BRQ4VV10XjODEAPYSop-7nUZU',
    appId: '1:1062359938217:web:6102a788aa0144941125b8',
    messagingSenderId: '1062359938217',
    projectId: 'e-labor-3ed98',
    authDomain: 'e-labor-3ed98.firebaseapp.com',
    databaseURL:
        'https://e-labor-3ed98-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-labor-3ed98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4f8jORnC1kVT9oH9lVcBNN-lrDLVjCSI',
    appId: '1:1062359938217:android:3e2754af00c21b1e1125b8',
    messagingSenderId: '1062359938217',
    projectId: 'e-labor-3ed98',
    databaseURL:
        'https://e-labor-3ed98-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-labor-3ed98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYP55n-BulnCPCSmhwIl_yNAlh_M11O1g',
    appId: '1:1062359938217:ios:74743dcda43073a11125b8',
    messagingSenderId: '1062359938217',
    projectId: 'e-labor-3ed98',
    databaseURL:
        'https://e-labor-3ed98-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-labor-3ed98.firebasestorage.app',
    iosBundleId: 'com.example.elabor',
  );
}
